Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.
default = [{
    id: "1",
    name: "湖北",
    mark: "H",
    en: "hubei",
    l2: [{
        id: "295",
        name: "武汉市",
        mark: "W",
        en: "wuhanshi"
    }, {
        id: "296",
        name: "黄石市",
        mark: "H",
        en: "huangshishi"
    }, {
        id: "297",
        name: "十堰市",
        mark: "S",
        en: "shiyanshi"
    }, {
        id: "298",
        name: "宜昌市",
        mark: "Y",
        en: "yichangshi"
    }, {
        id: "299",
        name: "襄樊市",
        mark: "X",
        en: "xiangfanshi"
    }, {
        id: "300",
        name: "鄂州市",
        mark: "E",
        en: "ezhoushi"
    }, {
        id: "301",
        name: "荆门市",
        mark: "J",
        en: "jingmenshi"
    }, {
        id: "302",
        name: "孝感市",
        mark: "X",
        en: "xiaoganshi"
    }, {
        id: "303",
        name: "荆州市",
        mark: "J",
        en: "jingzhoushi"
    }, {
        id: "304",
        name: "黄冈市",
        mark: "H",
        en: "huanggangshi"
    }, {
        id: "305",
        name: "咸宁市",
        mark: "X",
        en: "xianningshi"
    }, {
        id: "306",
        name: "随州市",
        mark: "S",
        en: "suizhoushi"
    }, {
        id: "307",
        name: "恩施市",
        mark: "E",
        en: "enshishi"
    }, {
        id: "308",
        name: "仙桃市",
        mark: "X",
        en: "xiantaoshi"
    }, {
        id: "309",
        name: "潜江市",
        mark: "Q",
        en: "qianjiangshi"
    }, {
        id: "310",
        name: "天门市",
        mark: "T",
        en: "tianmenshi"
    }, {
        id: "311",
        name: "神农架林区",
        mark: "S",
        en: "shennongjialinqu"
    }, {
        id: "538",
        name: "麻城",
        mark: "M",
        en: "macheng"
    }, {
        id: "539",
        name: "蕲春",
        mark: "Q",
        en: "qinchun"
    }, {
        id: "540",
        name: "监利",
        mark: "J",
        en: "jianli"
    }, {
        id: "541",
        name: "汉川",
        mark: "H",
        en: "hanchuan"
    }, {
        id: "542",
        name: "红安",
        mark: "H",
        en: "hongan"
    }, {
        id: "543",
        name: "松滋",
        mark: "S",
        en: "松滋"
    }]
}, {
    id: "2",
    name: "上海",
    mark: "S",
    en: "shanghai",
    l2: [{
        id: "53",
        name: "黄浦区",
        mark: "H",
        en: "huangpuqu"
    }, {
        id: "54",
        name: "卢湾区",
        mark: "L",
        en: "luwanqu"
    }, {
        id: "55",
        name: "徐汇区",
        mark: "X",
        en: "xuhuiqu"
    }, {
        id: "56",
        name: "长宁区",
        mark: "C",
        en: "changningqu"
    }, {
        id: "57",
        name: "静安区",
        mark: "J",
        en: "jinganqu"
    }, {
        id: "58",
        name: "普陀区",
        mark: "P",
        en: "putuoqu"
    }, {
        id: "59",
        name: "闸北区",
        mark: "Z",
        en: "zhabeiqu"
    }, {
        id: "60",
        name: "虹口区",
        mark: "H",
        en: "hongkouqu"
    }, {
        id: "61",
        name: "杨浦区",
        mark: "Y",
        en: "yangpuqu"
    }, {
        id: "62",
        name: "闵行区",
        mark: "M",
        en: "minxingqu"
    }, {
        id: "63",
        name: "宝山区",
        mark: "B",
        en: "baoshanqu"
    }, {
        id: "64",
        name: "嘉定区",
        mark: "J",
        en: "jiadingqu"
    }, {
        id: "65",
        name: "浦东新区",
        mark: "P",
        en: "pudongxinqu"
    }, {
        id: "66",
        name: "金山区",
        mark: "J",
        en: "jinshanqu"
    }, {
        id: "67",
        name: "松江区",
        mark: "S",
        en: "songjiangqu"
    }, {
        id: "68",
        name: "青浦区",
        mark: "Q",
        en: "qingpuqu"
    }, {
        id: "69",
        name: "南汇区",
        mark: "N",
        en: "nanhuiqu"
    }, {
        id: "70",
        name: "奉贤区",
        mark: "F",
        en: "fengxianqu"
    }, {
        id: "71",
        name: "崇明县",
        mark: "C",
        en: "chongmingxian"
    }]
}, {
    id: "3",
    name: "天津",
    mark: "T",
    en: "tianjin",
    l2: [{
        id: "72",
        name: "和平区",
        mark: "H",
        en: "hepingqu"
    }, {
        id: "73",
        name: "河东区",
        mark: "H",
        en: "hedongqu"
    }, {
        id: "74",
        name: "河西区",
        mark: "H",
        en: "hexiqu"
    }, {
        id: "75",
        name: "南开区",
        mark: "N",
        en: "nankaiqu"
    }, {
        id: "76",
        name: "河北区",
        mark: "H",
        en: "hebeiqu"
    }, {
        id: "77",
        name: "红桥区",
        mark: "H",
        en: "hongqiaoqu"
    }, {
        id: "78",
        name: "塘沽区",
        mark: "T",
        en: "tangguqu"
    }, {
        id: "79",
        name: "汉沽区",
        mark: "H",
        en: "hanguqu"
    }, {
        id: "80",
        name: "大港区",
        mark: "D",
        en: "dagangqu"
    }, {
        id: "81",
        name: "东丽区",
        mark: "D",
        en: "dongliqu"
    }, {
        id: "82",
        name: "西青区",
        mark: "X",
        en: "xiqingqu"
    }, {
        id: "83",
        name: "津南区",
        mark: "J",
        en: "jinnanqu"
    }, {
        id: "84",
        name: "北辰区",
        mark: "B",
        en: "beichenqu"
    }, {
        id: "85",
        name: "武清区",
        mark: "W",
        en: "wuqingqu"
    }, {
        id: "86",
        name: "宝坻区",
        mark: "B",
        en: "baodiqu"
    }, {
        id: "87",
        name: "宁河县",
        mark: "N",
        en: "ninghexian"
    }, {
        id: "88",
        name: "静海县",
        mark: "J",
        en: "jinghaixian"
    }, {
        id: "89",
        name: "蓟县",
        mark: "J",
        en: "jixian"
    }]
}, {
    id: "4",
    name: "重庆",
    mark: "Z",
    en: "zhongqing",
    l2: [{
        id: "90",
        name: "万州区",
        mark: "W",
        en: "wanzhouqu"
    }, {
        id: "91",
        name: "涪陵区",
        mark: "F",
        en: "fulingqu"
    }, {
        id: "92",
        name: "渝中区",
        mark: "Y",
        en: "yuzhongqu"
    }, {
        id: "93",
        name: "大渡口区",
        mark: "D",
        en: "dadukouqu"
    }, {
        id: "94",
        name: "江北区",
        mark: "J",
        en: "jiangbeiqu"
    }, {
        id: "95",
        name: "沙坪坝区",
        mark: "S",
        en: "shapingbaqu"
    }, {
        id: "96",
        name: "九龙坡区",
        mark: "J",
        en: "jiulongpoqu"
    }, {
        id: "97",
        name: "南岸区",
        mark: "N",
        en: "nananqu"
    }, {
        id: "98",
        name: "北碚区",
        mark: "B",
        en: "beibeiqu"
    }, {
        id: "99",
        name: "万盛区",
        mark: "W",
        en: "wanshengqu"
    }, {
        id: "100",
        name: "双桥区",
        mark: "S",
        en: "shuangqiaoqu"
    }, {
        id: "101",
        name: "渝北区",
        mark: "Y",
        en: "yubeiqu"
    }, {
        id: "102",
        name: "巴南区",
        mark: "B",
        en: "bananqu"
    }, {
        id: "103",
        name: "黔江区",
        mark: "Q",
        en: "qianjiangqu"
    }, {
        id: "104",
        name: "长寿区",
        mark: "C",
        en: "changshouqu"
    }, {
        id: "105",
        name: "綦江县",
        mark: "Q",
        en: "qijiangxian"
    }, {
        id: "106",
        name: "潼南县",
        mark: "T",
        en: "tongnanxian"
    }, {
        id: "107",
        name: "铜梁县",
        mark: "T",
        en: "tongliangxian"
    }, {
        id: "108",
        name: "大足县",
        mark: "D",
        en: "dazuxian"
    }, {
        id: "109",
        name: "荣昌县",
        mark: "R",
        en: "rongchangxian"
    }, {
        id: "110",
        name: "璧山县",
        mark: "B",
        en: "bishanxian"
    }, {
        id: "111",
        name: "梁平县",
        mark: "L",
        en: "liangpingxian"
    }, {
        id: "112",
        name: "城口县",
        mark: "C",
        en: "chengkouxian"
    }, {
        id: "113",
        name: "丰都县",
        mark: "F",
        en: "fengduxian"
    }, {
        id: "114",
        name: "垫江县",
        mark: "D",
        en: "dianjiangxian"
    }, {
        id: "115",
        name: "武隆县",
        mark: "W",
        en: "wulongxian"
    }, {
        id: "116",
        name: "忠县",
        mark: "Z",
        en: "zhongxian"
    }, {
        id: "117",
        name: "开县",
        mark: "K",
        en: "kaixian"
    }, {
        id: "118",
        name: "云阳县",
        mark: "Y",
        en: "yunyangxian"
    }, {
        id: "119",
        name: "奉节县",
        mark: "F",
        en: "fengjiexian"
    }, {
        id: "120",
        name: "巫山县",
        mark: "W",
        en: "wushanxian"
    }, {
        id: "121",
        name: "巫溪县",
        mark: "W",
        en: "wuxixian"
    }, {
        id: "122",
        name: "石柱",
        mark: "S",
        en: "shizhu"
    }, {
        id: "123",
        name: "秀山",
        mark: "X",
        en: "xiushan"
    }, {
        id: "124",
        name: "酉阳",
        mark: "Y",
        en: "youyang"
    }, {
        id: "125",
        name: "彭水",
        mark: "P",
        en: "pengshui"
    }, {
        id: "126",
        name: "江津市",
        mark: "J",
        en: "jiangjinshi"
    }, {
        id: "127",
        name: "合川市",
        mark: "H",
        en: "hechuanshi"
    }, {
        id: "128",
        name: "永川市",
        mark: "Y",
        en: "yongchuanshi"
    }, {
        id: "129",
        name: "南川市",
        mark: "N",
        en: "nanchuanshi"
    }]
}, {
    id: "5",
    name: "河北",
    mark: "H",
    en: "hebei",
    l2: [{
        id: "130",
        name: "石家庄市",
        mark: "S",
        en: "shijiazhuangshi"
    }, {
        id: "131",
        name: "唐山市",
        mark: "T",
        en: "tangshanshi"
    }, {
        id: "132",
        name: "秦皇岛市",
        mark: "Q",
        en: "qinhuangdaoshi"
    }, {
        id: "133",
        name: "邯郸市",
        mark: "H",
        en: "handanshi"
    }, {
        id: "134",
        name: "邢台市",
        mark: "X",
        en: "xingtaishi"
    }, {
        id: "135",
        name: "保定市",
        mark: "B",
        en: "baodingshi"
    }, {
        id: "136",
        name: "张家口市",
        mark: "Z",
        en: "zhangjiakoushi"
    }, {
        id: "137",
        name: "承德市",
        mark: "C",
        en: "chengdeshi"
    }, {
        id: "138",
        name: "沧州市",
        mark: "C",
        en: "cangzhoushi"
    }, {
        id: "139",
        name: "廊坊市",
        mark: "L",
        en: "langfangshi"
    }, {
        id: "140",
        name: "衡水市",
        mark: "H",
        en: "hengshuishi"
    }]
}, {
    id: "6",
    name: "山西",
    mark: "S",
    en: "shanxi",
    l2: [{
        id: "141",
        name: "太原市",
        mark: "T",
        en: "taiyuanshi"
    }, {
        id: "142",
        name: "大同市",
        mark: "D",
        en: "datongshi"
    }, {
        id: "143",
        name: "阳泉市",
        mark: "Y",
        en: "yangquanshi"
    }, {
        id: "144",
        name: "长治市",
        mark: "C",
        en: "changzhishi"
    }, {
        id: "145",
        name: "晋城市",
        mark: "J",
        en: "jinchengshi"
    }, {
        id: "146",
        name: "朔州市",
        mark: "S",
        en: "shuozhoushi"
    }, {
        id: "147",
        name: "晋中市",
        mark: "J",
        en: "jinzhongshi"
    }, {
        id: "148",
        name: "运城市",
        mark: "Y",
        en: "yunchengshi"
    }, {
        id: "149",
        name: "忻州市",
        mark: "X",
        en: "xinzhoushi"
    }, {
        id: "150",
        name: "临汾市",
        mark: "L",
        en: "linfenshi"
    }, {
        id: "151",
        name: "吕梁市",
        mark: "L",
        en: "lvliangshi"
    }]
}, {
    id: "7",
    name: "内蒙古",
    mark: "N",
    en: "namenggu",
    l2: [{
        id: "152",
        name: "呼和浩特市",
        mark: "H",
        en: "huhehaoteshi"
    }, {
        id: "153",
        name: "包头市",
        mark: "B",
        en: "baotoushi"
    }, {
        id: "154",
        name: "乌海市",
        mark: "W",
        en: "wuhaishi"
    }, {
        id: "155",
        name: "赤峰市",
        mark: "C",
        en: "chifengshi"
    }, {
        id: "156",
        name: "通辽市",
        mark: "T",
        en: "tongliaoshi"
    }, {
        id: "157",
        name: "鄂尔多斯市",
        mark: "E",
        en: "eerduosishi"
    }, {
        id: "158",
        name: "呼伦贝尔市",
        mark: "H",
        en: "hulunbeiershi"
    }, {
        id: "159",
        name: "巴彦淖尔市",
        mark: "B",
        en: "bayanneershi"
    }, {
        id: "160",
        name: "乌兰察布市",
        mark: "W",
        en: "wulanchabushi"
    }, {
        id: "161",
        name: "兴安盟",
        mark: "X",
        en: "xinganmeng"
    }, {
        id: "162",
        name: "锡林郭勒盟",
        mark: "X",
        en: "xilinguolemeng"
    }, {
        id: "163",
        name: "阿拉善盟",
        mark: "A",
        en: "alashanmeng"
    }]
}, {
    id: "8",
    name: "辽宁",
    mark: "L",
    en: "liaoning",
    l2: [{
        id: "164",
        name: "沈阳市",
        mark: "S",
        en: "shenyangshi"
    }, {
        id: "165",
        name: "大连市",
        mark: "D",
        en: "dalianshi"
    }, {
        id: "166",
        name: "鞍山市",
        mark: "A",
        en: "anshanshi"
    }, {
        id: "167",
        name: "抚顺市",
        mark: "F",
        en: "fushunshi"
    }, {
        id: "168",
        name: "本溪市",
        mark: "B",
        en: "benxishi"
    }, {
        id: "169",
        name: "丹东市",
        mark: "D",
        en: "dandongshi"
    }, {
        id: "170",
        name: "锦州市",
        mark: "J",
        en: "jinzhoushi"
    }, {
        id: "171",
        name: "营口市",
        mark: "Y",
        en: "yingkoushi"
    }, {
        id: "172",
        name: "阜新市",
        mark: "F",
        en: "fuxinshi"
    }, {
        id: "173",
        name: "辽阳市",
        mark: "L",
        en: "liaoyangshi"
    }, {
        id: "174",
        name: "盘锦市",
        mark: "P",
        en: "panjinshi"
    }, {
        id: "175",
        name: "铁岭市",
        mark: "T",
        en: "tielingshi"
    }, {
        id: "176",
        name: "朝阳市",
        mark: "C",
        en: "chaoyangshi"
    }, {
        id: "177",
        name: "葫芦岛市",
        mark: "H",
        en: "huludaoshi"
    }]
}, {
    id: "9",
    name: "吉林",
    mark: "J",
    en: "jilin",
    l2: [{
        id: "178",
        name: "长春市",
        mark: "C",
        en: "changchunshi"
    }, {
        id: "179",
        name: "吉林市",
        mark: "J",
        en: "jilinshi"
    }, {
        id: "180",
        name: "四平市",
        mark: "S",
        en: "sipingshi"
    }, {
        id: "181",
        name: "辽源市",
        mark: "L",
        en: "liaoyuanshi"
    }, {
        id: "182",
        name: "通化市",
        mark: "T",
        en: "tonghuashi"
    }, {
        id: "183",
        name: "白山市",
        mark: "B",
        en: "baishanshi"
    }, {
        id: "184",
        name: "松原市",
        mark: "S",
        en: "songyuanshi"
    }, {
        id: "185",
        name: "白城市",
        mark: "B",
        en: "baichengshi"
    }, {
        id: "186",
        name: "延边市",
        mark: "Y",
        en: "yanbianshi"
    }]
}, {
    id: "10",
    name: "黑龙江",
    mark: "H",
    en: "heilongjiang",
    l2: [{
        id: "187",
        name: "哈尔滨市",
        mark: "H",
        en: "haerbinshi"
    }, {
        id: "188",
        name: "齐齐哈尔市",
        mark: "Q",
        en: "qiqihaershi"
    }, {
        id: "189",
        name: "鸡西市",
        mark: "J",
        en: "jixishi"
    }, {
        id: "190",
        name: "鹤岗市",
        mark: "H",
        en: "hegangshi"
    }, {
        id: "191",
        name: "双鸭山市",
        mark: "S",
        en: "shuangyashanshi"
    }, {
        id: "192",
        name: "大庆市",
        mark: "D",
        en: "daqingshi"
    }, {
        id: "193",
        name: "伊春市",
        mark: "Y",
        en: "yichunshi"
    }, {
        id: "194",
        name: "佳木斯市",
        mark: "J",
        en: "jiamusishi"
    }, {
        id: "195",
        name: "七台河市",
        mark: "Q",
        en: "qitaiheshi"
    }, {
        id: "196",
        name: "牡丹江市",
        mark: "M",
        en: "mudanjiangshi"
    }, {
        id: "197",
        name: "黑河市",
        mark: "H",
        en: "heiheshi"
    }, {
        id: "198",
        name: "绥化市",
        mark: "S",
        en: "suihuashi"
    }, {
        id: "199",
        name: "大兴安岭",
        mark: "D",
        en: "daxinganling"
    }]
}, {
    id: "11",
    name: "江苏",
    mark: "J",
    en: "jiangsu",
    l2: [{
        id: "200",
        name: "南京市",
        mark: "N",
        en: "nanjingshi"
    }, {
        id: "201",
        name: "无锡市",
        mark: "W",
        en: "wuxishi"
    }, {
        id: "202",
        name: "徐州市",
        mark: "X",
        en: "xuzhoushi"
    }, {
        id: "203",
        name: "常州市",
        mark: "C",
        en: "changzhoushi"
    }, {
        id: "204",
        name: "苏州市",
        mark: "S",
        en: "suzhoushi"
    }, {
        id: "205",
        name: "南通市",
        mark: "N",
        en: "nantongshi"
    }, {
        id: "206",
        name: "连云港市",
        mark: "L",
        en: "lianyungangshi"
    }, {
        id: "207",
        name: "淮安市",
        mark: "H",
        en: "huaianshi"
    }, {
        id: "208",
        name: "盐城市",
        mark: "Y",
        en: "yanchengshi"
    }, {
        id: "209",
        name: "扬州市",
        mark: "Y",
        en: "yangzhoushi"
    }, {
        id: "210",
        name: "镇江市",
        mark: "Z",
        en: "zhenjiangshi"
    }, {
        id: "211",
        name: "泰州市",
        mark: "T",
        en: "taizhoushi"
    }, {
        id: "212",
        name: "宿迁市",
        mark: "S",
        en: "suqianshi"
    }]
}, {
    id: "12",
    name: "浙江",
    mark: "Z",
    en: "zhejiang",
    l2: [{
        id: "213",
        name: "杭州市",
        mark: "H",
        en: "hangzhoushi"
    }, {
        id: "214",
        name: "宁波市",
        mark: "N",
        en: "ningboshi"
    }, {
        id: "215",
        name: "温州市",
        mark: "W",
        en: "wenzhoushi"
    }, {
        id: "216",
        name: "嘉兴市",
        mark: "J",
        en: "jiaxingshi"
    }, {
        id: "217",
        name: "湖州市",
        mark: "H",
        en: "huzhoushi"
    }, {
        id: "218",
        name: "绍兴市",
        mark: "S",
        en: "shaoxingshi"
    }, {
        id: "219",
        name: "金华市",
        mark: "J",
        en: "jinhuashi"
    }, {
        id: "220",
        name: "衢州市",
        mark: "Q",
        en: "quzhoushi"
    }, {
        id: "221",
        name: "舟山市",
        mark: "Z",
        en: "zhoushanshi"
    }, {
        id: "222",
        name: "台州市",
        mark: "T",
        en: "taizhoushi"
    }, {
        id: "223",
        name: "丽水市",
        mark: "L",
        en: "lishuishi"
    }]
}, {
    id: "13",
    name: "安徽",
    mark: "A",
    en: "anhui",
    l2: [{
        id: "224",
        name: "合肥市",
        mark: "H",
        en: "hefeishi"
    }, {
        id: "225",
        name: "芜湖市",
        mark: "W",
        en: "wuhushi"
    }, {
        id: "226",
        name: "蚌埠市",
        mark: "B",
        en: "bangbushi"
    }, {
        id: "227",
        name: "淮南市",
        mark: "H",
        en: "huainanshi"
    }, {
        id: "228",
        name: "马鞍山市",
        mark: "M",
        en: "maanshanshi"
    }, {
        id: "229",
        name: "淮北市",
        mark: "H",
        en: "huaibeishi"
    }, {
        id: "230",
        name: "铜陵市",
        mark: "T",
        en: "tonglingshi"
    }, {
        id: "231",
        name: "安庆市",
        mark: "A",
        en: "anqingshi"
    }, {
        id: "232",
        name: "黄山市",
        mark: "H",
        en: "huangshanshi"
    }, {
        id: "233",
        name: "滁州市",
        mark: "C",
        en: "chuzhoushi"
    }, {
        id: "234",
        name: "阜阳市",
        mark: "F",
        en: "fuyangshi"
    }, {
        id: "235",
        name: "宿州市",
        mark: "S",
        en: "suzhoushi"
    }, {
        id: "236",
        name: "巢湖市",
        mark: "C",
        en: "chaohushi"
    }, {
        id: "237",
        name: "六安市",
        mark: "L",
        en: "liuanshi"
    }, {
        id: "238",
        name: "亳州市",
        mark: "B",
        en: "bozhoushi"
    }, {
        id: "239",
        name: "池州市",
        mark: "C",
        en: "chizhoushi"
    }, {
        id: "240",
        name: "宣城市",
        mark: "X",
        en: "xuanchengshi"
    }]
}, {
    id: "14",
    name: "福建",
    mark: "F",
    en: "fujian",
    l2: [{
        id: "241",
        name: "福州市",
        mark: "F",
        en: "fuzhoushi"
    }, {
        id: "242",
        name: "厦门市",
        mark: "X",
        en: "xiamenshi"
    }, {
        id: "243",
        name: "莆田市",
        mark: "P",
        en: "putianshi"
    }, {
        id: "244",
        name: "三明市",
        mark: "S",
        en: "sanmingshi"
    }, {
        id: "245",
        name: "泉州市",
        mark: "Q",
        en: "quanzhoushi"
    }, {
        id: "246",
        name: "漳州市",
        mark: "Z",
        en: "zhangzhoushi"
    }, {
        id: "247",
        name: "南平市",
        mark: "N",
        en: "nanpingshi"
    }, {
        id: "248",
        name: "龙岩市",
        mark: "L",
        en: "longyanshi"
    }, {
        id: "249",
        name: "宁德市",
        mark: "N",
        en: "ningdeshi"
    }]
}, {
    id: "15",
    name: "江西",
    mark: "J",
    en: "jiangxi",
    l2: [{
        id: "250",
        name: "南昌市",
        mark: "N",
        en: "nanchangshi"
    }, {
        id: "251",
        name: "景德镇市",
        mark: "J",
        en: "jingdezhenshi"
    }, {
        id: "252",
        name: "萍乡市",
        mark: "P",
        en: "pingxiangshi"
    }, {
        id: "253",
        name: "九江市",
        mark: "J",
        en: "jiujiangshi"
    }, {
        id: "254",
        name: "新余市",
        mark: "X",
        en: "xinyushi"
    }, {
        id: "255",
        name: "鹰潭市",
        mark: "Y",
        en: "yingtanshi"
    }, {
        id: "256",
        name: "赣州市",
        mark: "G",
        en: "ganzhoushi"
    }, {
        id: "257",
        name: "吉安市",
        mark: "J",
        en: "jianshi"
    }, {
        id: "258",
        name: "宜春市",
        mark: "Y",
        en: "yichunshi"
    }, {
        id: "259",
        name: "抚州市",
        mark: "F",
        en: "fuzhoushi"
    }, {
        id: "260",
        name: "上饶市",
        mark: "S",
        en: "shangraoshi"
    }]
}, {
    id: "16",
    name: "山东",
    mark: "S",
    en: "shandong",
    l2: [{
        id: "261",
        name: "济南市",
        mark: "J",
        en: "jinanshi"
    }, {
        id: "262",
        name: "青岛市",
        mark: "Q",
        en: "qingdaoshi"
    }, {
        id: "263",
        name: "淄博市",
        mark: "Z",
        en: "ziboshi"
    }, {
        id: "264",
        name: "枣庄市",
        mark: "Z",
        en: "zaozhuangshi"
    }, {
        id: "265",
        name: "东营市",
        mark: "D",
        en: "dongyingshi"
    }, {
        id: "266",
        name: "烟台市",
        mark: "Y",
        en: "yantaishi"
    }, {
        id: "267",
        name: "潍坊市",
        mark: "W",
        en: "weifangshi"
    }, {
        id: "268",
        name: "济宁市",
        mark: "J",
        en: "jiningshi"
    }, {
        id: "269",
        name: "泰安市",
        mark: "T",
        en: "taianshi"
    }, {
        id: "270",
        name: "威海市",
        mark: "W",
        en: "weihaishi"
    }, {
        id: "271",
        name: "日照市",
        mark: "R",
        en: "rizhaoshi"
    }, {
        id: "272",
        name: "莱芜市",
        mark: "L",
        en: "laiwushi"
    }, {
        id: "273",
        name: "临沂市",
        mark: "L",
        en: "linyishi"
    }, {
        id: "274",
        name: "德州市",
        mark: "D",
        en: "dezhoushi"
    }, {
        id: "275",
        name: "聊城市",
        mark: "L",
        en: "liaochengshi"
    }, {
        id: "276",
        name: "滨州市",
        mark: "B",
        en: "binzhoushi"
    }, {
        id: "277",
        name: "荷泽市",
        mark: "H",
        en: "hezeshi"
    }]
}, {
    id: "17",
    name: "河南",
    mark: "H",
    en: "henan",
    l2: [{
        id: "278",
        name: "郑州市",
        mark: "Z",
        en: "zhengzhoushi"
    }, {
        id: "279",
        name: "开封市",
        mark: "K",
        en: "kaifengshi"
    }, {
        id: "280",
        name: "洛阳市",
        mark: "L",
        en: "luoyangshi"
    }, {
        id: "281",
        name: "平顶山市",
        mark: "P",
        en: "pingdingshanshi"
    }, {
        id: "282",
        name: "安阳市",
        mark: "A",
        en: "anyangshi"
    }, {
        id: "283",
        name: "鹤壁市",
        mark: "H",
        en: "hebishi"
    }, {
        id: "284",
        name: "新乡市",
        mark: "X",
        en: "xinxiangshi"
    }, {
        id: "285",
        name: "焦作市",
        mark: "J",
        en: "jiaozuoshi"
    }, {
        id: "286",
        name: "濮阳市",
        mark: "P",
        en: "puyangshi"
    }, {
        id: "287",
        name: "许昌市",
        mark: "X",
        en: "xuchangshi"
    }, {
        id: "288",
        name: "漯河市",
        mark: "L",
        en: "leiheshi"
    }, {
        id: "289",
        name: "三门峡市",
        mark: "S",
        en: "sanmenxiashi"
    }, {
        id: "290",
        name: "南阳市",
        mark: "N",
        en: "nanyangshi"
    }, {
        id: "291",
        name: "商丘市",
        mark: "S",
        en: "shangqiushi"
    }, {
        id: "292",
        name: "信阳市",
        mark: "X",
        en: "xinyangshi"
    }, {
        id: "293",
        name: "周口市",
        mark: "Z",
        en: "zhoukoushi"
    }, {
        id: "294",
        name: "驻马店市",
        mark: "Z",
        en: "zhumadianshi"
    }]
}, {
    id: "18",
    name: "北京",
    mark: "B",
    en: "beijing",
    l2: [{
        id: "35",
        name: "东城区",
        mark: "D",
        en: "dongchengqu"
    }, {
        id: "36",
        name: "西城区",
        mark: "X",
        en: "xichengqu"
    }, {
        id: "37",
        name: "崇文区",
        mark: "C",
        en: "chongwenqu"
    }, {
        id: "38",
        name: "宣武区",
        mark: "X",
        en: "xuanwuqu"
    }, {
        id: "39",
        name: "朝阳区",
        mark: "C",
        en: "chaoyangqu"
    }, {
        id: "40",
        name: "丰台区",
        mark: "F",
        en: "fengtaiqu"
    }, {
        id: "41",
        name: "石景山区",
        mark: "S",
        en: "shijingshanqu"
    }, {
        id: "42",
        name: "海淀区",
        mark: "H",
        en: "haidianqu"
    }, {
        id: "43",
        name: "门头沟区",
        mark: "M",
        en: "mentougouqu"
    }, {
        id: "44",
        name: "房山区",
        mark: "F",
        en: "fangshanqu"
    }, {
        id: "45",
        name: "通州区",
        mark: "T",
        en: "tongzhouqu"
    }, {
        id: "46",
        name: "顺义区",
        mark: "S",
        en: "shunyiqu"
    }, {
        id: "47",
        name: "昌平区",
        mark: "C",
        en: "changpingqu"
    }, {
        id: "48",
        name: "大兴区",
        mark: "D",
        en: "daxingqu"
    }, {
        id: "49",
        name: "怀柔区",
        mark: "H",
        en: "huairouqu"
    }, {
        id: "50",
        name: "平谷区",
        mark: "P",
        en: "pingguqu"
    }, {
        id: "51",
        name: "密云县",
        mark: "M",
        en: "miyunxian"
    }, {
        id: "52",
        name: "延庆县",
        mark: "Y",
        en: "yanqingxian"
    }]
}, {
    id: "19",
    name: "湖南",
    mark: "H",
    en: "hunan",
    l2: [{
        id: "312",
        name: "长沙市",
        mark: "C",
        en: "changshashi"
    }, {
        id: "313",
        name: "株洲市",
        mark: "Z",
        en: "zhuzhoushi"
    }, {
        id: "314",
        name: "湘潭市",
        mark: "X",
        en: "xiangtanshi"
    }, {
        id: "315",
        name: "衡阳市",
        mark: "H",
        en: "hengyangshi"
    }, {
        id: "316",
        name: "邵阳市",
        mark: "S",
        en: "shaoyangshi"
    }, {
        id: "317",
        name: "岳阳市",
        mark: "Y",
        en: "yueyangshi"
    }, {
        id: "318",
        name: "常德市",
        mark: "C",
        en: "changdeshi"
    }, {
        id: "319",
        name: "张家界市",
        mark: "Z",
        en: "zhangjiajieshi"
    }, {
        id: "320",
        name: "益阳市",
        mark: "Y",
        en: "yiyangshi"
    }, {
        id: "321",
        name: "郴州市",
        mark: "C",
        en: "chenzhoushi"
    }, {
        id: "322",
        name: "永州市",
        mark: "Y",
        en: "yongzhoushi"
    }, {
        id: "323",
        name: "怀化市",
        mark: "H",
        en: "huaihuashi"
    }, {
        id: "324",
        name: "娄底市",
        mark: "L",
        en: "loudishi"
    }, {
        id: "325",
        name: "湘西",
        mark: "X",
        en: "xiangxi"
    }]
}, {
    id: "20",
    name: "广东",
    mark: "G",
    en: "guangdong",
    l2: [{
        id: "326",
        name: "广州市",
        mark: "G",
        en: "guangzhoushi"
    }, {
        id: "327",
        name: "韶关市",
        mark: "S",
        en: "shaoguanshi"
    }, {
        id: "328",
        name: "深圳市",
        mark: "S",
        en: "shenchoushi"
    }, {
        id: "329",
        name: "珠海市",
        mark: "Z",
        en: "zhuhaishi"
    }, {
        id: "330",
        name: "汕头市",
        mark: "S",
        en: "shantoushi"
    }, {
        id: "331",
        name: "佛山市",
        mark: "F",
        en: "fushanshi"
    }, {
        id: "332",
        name: "江门市",
        mark: "J",
        en: "jiangmenshi"
    }, {
        id: "333",
        name: "湛江市",
        mark: "Z",
        en: "zhanjiangshi"
    }, {
        id: "334",
        name: "茂名市",
        mark: "M",
        en: "maomingshi"
    }, {
        id: "335",
        name: "肇庆市",
        mark: "Z",
        en: "zhaoqingshi"
    }, {
        id: "336",
        name: "惠州市",
        mark: "H",
        en: "huizhoushi"
    }, {
        id: "337",
        name: "梅州市",
        mark: "M",
        en: "meizhoushi"
    }, {
        id: "338",
        name: "汕尾市",
        mark: "S",
        en: "shanweishi"
    }, {
        id: "339",
        name: "河源市",
        mark: "H",
        en: "heyuanshi"
    }, {
        id: "340",
        name: "阳江市",
        mark: "Y",
        en: "yangjiangshi"
    }, {
        id: "341",
        name: "清远市",
        mark: "Q",
        en: "qingyuanshi"
    }, {
        id: "342",
        name: "东莞市",
        mark: "D",
        en: "dongguanshi"
    }, {
        id: "343",
        name: "中山市",
        mark: "Z",
        en: "zhongshanshi"
    }, {
        id: "344",
        name: "潮州市",
        mark: "C",
        en: "chaozhoushi"
    }, {
        id: "345",
        name: "揭阳市",
        mark: "J",
        en: "jieyangshi"
    }, {
        id: "346",
        name: "云浮市",
        mark: "Y",
        en: "yunfushi"
    }]
}, {
    id: "21",
    name: "广西",
    mark: "G",
    en: "guangxi",
    l2: [{
        id: "347",
        name: "南宁市",
        mark: "N",
        en: "nanningshi"
    }, {
        id: "348",
        name: "柳州市",
        mark: "L",
        en: "liuzhoushi"
    }, {
        id: "349",
        name: "桂林市",
        mark: "G",
        en: "guilinshi"
    }, {
        id: "350",
        name: "梧州市",
        mark: "W",
        en: "wuzhoushi"
    }, {
        id: "351",
        name: "北海市",
        mark: "B",
        en: "beihaishi"
    }, {
        id: "352",
        name: "防城港市",
        mark: "F",
        en: "fangchenggangshi"
    }, {
        id: "353",
        name: "钦州市",
        mark: "Q",
        en: "qinzhoushi"
    }, {
        id: "354",
        name: "贵港市",
        mark: "G",
        en: "guigangshi"
    }, {
        id: "355",
        name: "玉林市",
        mark: "Y",
        en: "yulinshi"
    }, {
        id: "356",
        name: "百色市",
        mark: "B",
        en: "baiseshi"
    }, {
        id: "357",
        name: "贺州市",
        mark: "H",
        en: "hezhoushi"
    }, {
        id: "358",
        name: "河池市",
        mark: "H",
        en: "hechishi"
    }, {
        id: "359",
        name: "来宾市",
        mark: "L",
        en: "laibinshi"
    }, {
        id: "360",
        name: "崇左市",
        mark: "C",
        en: "chongzuoshi"
    }]
}, {
    id: "22",
    name: "海南",
    mark: "H",
    en: "hainan",
    l2: [{
        id: "361",
        name: "海口市",
        mark: "H",
        en: "haikoushi"
    }, {
        id: "362",
        name: "三亚市",
        mark: "S",
        en: "sanyashi"
    }, {
        id: "363",
        name: "五指山市",
        mark: "W",
        en: "wuzhishanshi"
    }, {
        id: "364",
        name: "琼海市",
        mark: "Q",
        en: "qionghaishi"
    }, {
        id: "365",
        name: "儋州市",
        mark: "D",
        en: "danzhoushi"
    }, {
        id: "366",
        name: "文昌市",
        mark: "W",
        en: "wenchangshi"
    }, {
        id: "367",
        name: "万宁市",
        mark: "W",
        en: "wanningshi"
    }, {
        id: "368",
        name: "东方市",
        mark: "D",
        en: "dongfangshi"
    }, {
        id: "369",
        name: "定安县",
        mark: "D",
        en: "dinganxian"
    }, {
        id: "370",
        name: "屯昌县",
        mark: "T",
        en: "tunchangxian"
    }, {
        id: "371",
        name: "澄迈县",
        mark: "C",
        en: "chengmaixian"
    }, {
        id: "372",
        name: "临高县",
        mark: "L",
        en: "lingaoxian"
    }, {
        id: "373",
        name: "白沙",
        mark: "B",
        en: "baisha"
    }, {
        id: "374",
        name: "昌江",
        mark: "C",
        en: "changjiang"
    }, {
        id: "375",
        name: "乐东",
        mark: "L",
        en: "ledong"
    }, {
        id: "376",
        name: "陵水",
        mark: "L",
        en: "lingshui"
    }, {
        id: "377",
        name: "保亭",
        mark: "B",
        en: "baoting"
    }, {
        id: "378",
        name: "琼中",
        mark: "Q",
        en: "qiongzhong"
    }, {
        id: "379",
        name: "西沙群岛",
        mark: "X",
        en: "xishaqundao"
    }, {
        id: "380",
        name: "南沙群岛",
        mark: "N",
        en: "nanshaqundao"
    }, {
        id: "381",
        name: "中沙群岛",
        mark: "Z",
        en: "zhongshaqundao"
    }]
}, {
    id: "23",
    name: "四川",
    mark: "S",
    en: "sichuan",
    l2: [{
        id: "382",
        name: "成都市",
        mark: "C",
        en: "chengdushi"
    }, {
        id: "383",
        name: "自贡市",
        mark: "Z",
        en: "zigongshi"
    }, {
        id: "384",
        name: "攀枝花市",
        mark: "P",
        en: "panzhihuashi"
    }, {
        id: "385",
        name: "泸州市",
        mark: "L",
        en: "luzhoushi"
    }, {
        id: "386",
        name: "德阳市",
        mark: "D",
        en: "deyangshi"
    }, {
        id: "387",
        name: "绵阳市",
        mark: "M",
        en: "mianyangshi"
    }, {
        id: "388",
        name: "广元市",
        mark: "G",
        en: "guangyuanshi"
    }, {
        id: "389",
        name: "遂宁市",
        mark: "S",
        en: "suiningshi"
    }, {
        id: "390",
        name: "内江市",
        mark: "N",
        en: "najiangshi"
    }, {
        id: "391",
        name: "乐山市",
        mark: "L",
        en: "leshanshi"
    }, {
        id: "392",
        name: "南充市",
        mark: "N",
        en: "nanchongshi"
    }, {
        id: "393",
        name: "眉山市",
        mark: "M",
        en: "meishanshi"
    }, {
        id: "394",
        name: "宜宾市",
        mark: "Y",
        en: "yibinshi"
    }, {
        id: "395",
        name: "广安市",
        mark: "G",
        en: "guanganshi"
    }, {
        id: "396",
        name: "达州市",
        mark: "D",
        en: "dazhoushi"
    }, {
        id: "397",
        name: "雅安市",
        mark: "Y",
        en: "yaanshi"
    }, {
        id: "398",
        name: "巴中市",
        mark: "B",
        en: "bazhongshi"
    }, {
        id: "399",
        name: "资阳市",
        mark: "Z",
        en: "ziyangshi"
    }, {
        id: "400",
        name: "阿坝",
        mark: "A",
        en: "aba"
    }, {
        id: "401",
        name: "甘孜",
        mark: "G",
        en: "ganzi"
    }, {
        id: "402",
        name: "凉山",
        mark: "L",
        en: "liangshan"
    }]
}, {
    id: "24",
    name: "贵州",
    mark: "G",
    en: "guizhou",
    l2: [{
        id: "403",
        name: "贵阳市",
        mark: "G",
        en: "guiyangshi"
    }, {
        id: "404",
        name: "六盘水市",
        mark: "L",
        en: "liupanshuishi"
    }, {
        id: "405",
        name: "遵义市",
        mark: "Z",
        en: "zunyishi"
    }, {
        id: "406",
        name: "安顺市",
        mark: "A",
        en: "anshunshi"
    }, {
        id: "407",
        name: "铜仁地区",
        mark: "T",
        en: "tongrendiqu"
    }, {
        id: "408",
        name: "黔西南州",
        mark: "Q",
        en: "qianxinanzhou"
    }, {
        id: "409",
        name: "毕节地区",
        mark: "B",
        en: "bijiediqu"
    }, {
        id: "410",
        name: "黔东南州",
        mark: "Q",
        en: "qiandongnanzhou"
    }, {
        id: "411",
        name: "黔南州",
        mark: "Q",
        en: "qiannanzhou"
    }]
}, {
    id: "25",
    name: "云南",
    mark: "Y",
    en: "yunnan",
    l2: [{
        id: "412",
        name: "昆明市",
        mark: "K",
        en: "kunmingshi"
    }, {
        id: "413",
        name: "曲靖市",
        mark: "Q",
        en: "qujingshi"
    }, {
        id: "414",
        name: "玉溪市",
        mark: "Y",
        en: "yuxishi"
    }, {
        id: "415",
        name: "保山市",
        mark: "B",
        en: "baoshanshi"
    }, {
        id: "416",
        name: "昭通市",
        mark: "Z",
        en: "zhaotongshi"
    }, {
        id: "417",
        name: "丽江市",
        mark: "L",
        en: "lijiangshi"
    }, {
        id: "418",
        name: "思茅市",
        mark: "S",
        en: "simaoshi"
    }, {
        id: "419",
        name: "临沧市",
        mark: "L",
        en: "lincangshi"
    }, {
        id: "420",
        name: "楚雄",
        mark: "C",
        en: "chuxiong"
    }, {
        id: "421",
        name: "红河州",
        mark: "H",
        en: "honghezhou"
    }, {
        id: "422",
        name: "文山州",
        mark: "W",
        en: "wenshanzhou"
    }, {
        id: "423",
        name: "西双版纳州",
        mark: "X",
        en: "xishuangbannazhou"
    }, {
        id: "424",
        name: "大理州",
        mark: "D",
        en: "dalizhou"
    }, {
        id: "425",
        name: "德宏州",
        mark: "D",
        en: "dehongzhou"
    }, {
        id: "426",
        name: "怒江州",
        mark: "N",
        en: "nujiangzhou"
    }, {
        id: "427",
        name: "迪庆州",
        mark: "D",
        en: "diqingzhou"
    }]
}, {
    id: "26",
    name: "西藏",
    mark: "X",
    en: "xicang",
    l2: [{
        id: "428",
        name: "拉萨市",
        mark: "L",
        en: "lasashi"
    }, {
        id: "429",
        name: "昌都地区",
        mark: "C",
        en: "changdudiqu"
    }, {
        id: "430",
        name: "山南地区",
        mark: "S",
        en: "shannandiqu"
    }, {
        id: "431",
        name: "日喀则地区",
        mark: "R",
        en: "rikazediqu"
    }, {
        id: "432",
        name: "那曲地区",
        mark: "N",
        en: "naqudiqu"
    }, {
        id: "433",
        name: "阿里地区",
        mark: "A",
        en: "alidiqu"
    }, {
        id: "434",
        name: "林芝地区",
        mark: "L",
        en: "linzhidiqu"
    }]
}, {
    id: "27",
    name: "陕西",
    mark: "S",
    en: "shanxi",
    l2: [{
        id: "435",
        name: "西安市",
        mark: "X",
        en: "xianshi"
    }, {
        id: "436",
        name: "铜川市",
        mark: "T",
        en: "tongchuanshi"
    }, {
        id: "437",
        name: "宝鸡市",
        mark: "B",
        en: "baojishi"
    }, {
        id: "438",
        name: "咸阳市",
        mark: "X",
        en: "xianyangshi"
    }, {
        id: "439",
        name: "渭南市",
        mark: "W",
        en: "weinanshi"
    }, {
        id: "440",
        name: "延安市",
        mark: "Y",
        en: "yananshi"
    }, {
        id: "441",
        name: "汉中市",
        mark: "H",
        en: "hanzhongshi"
    }, {
        id: "442",
        name: "榆林市",
        mark: "Y",
        en: "yulinshi"
    }, {
        id: "443",
        name: "安康市",
        mark: "A",
        en: "ankangshi"
    }, {
        id: "444",
        name: "商洛市",
        mark: "S",
        en: "shangluoshi"
    }]
}, {
    id: "28",
    name: "甘肃",
    mark: "G",
    en: "gansu",
    l2: [{
        id: "445",
        name: "兰州市",
        mark: "L",
        en: "lanzhoushi"
    }, {
        id: "446",
        name: "嘉峪关市",
        mark: "J",
        en: "jiayuguanshi"
    }, {
        id: "447",
        name: "金昌市",
        mark: "J",
        en: "jinchangshi"
    }, {
        id: "448",
        name: "白银市",
        mark: "B",
        en: "baiyinshi"
    }, {
        id: "449",
        name: "天水市",
        mark: "T",
        en: "tianshuishi"
    }, {
        id: "450",
        name: "武威市",
        mark: "W",
        en: "wuweishi"
    }, {
        id: "451",
        name: "张掖市",
        mark: "Z",
        en: "zhangyeshi"
    }, {
        id: "452",
        name: "平凉市",
        mark: "P",
        en: "pingliangshi"
    }, {
        id: "453",
        name: "酒泉市",
        mark: "J",
        en: "jiuquanshi"
    }, {
        id: "454",
        name: "庆阳市",
        mark: "Q",
        en: "qingyangshi"
    }, {
        id: "455",
        name: "定西市",
        mark: "D",
        en: "dingxishi"
    }, {
        id: "456",
        name: "陇南市",
        mark: "L",
        en: "longnanshi"
    }, {
        id: "457",
        name: "临夏",
        mark: "L",
        en: "linxia"
    }, {
        id: "458",
        name: "甘南",
        mark: "G",
        en: "gannan"
    }]
}, {
    id: "29",
    name: "青海",
    mark: "Q",
    en: "qinghai",
    l2: [{
        id: "459",
        name: "西宁市",
        mark: "X",
        en: "xiningshi"
    }, {
        id: "460",
        name: "海东地区",
        mark: "H",
        en: "haidongdiqu"
    }, {
        id: "461",
        name: "海北州",
        mark: "H",
        en: "haibeizhou"
    }, {
        id: "462",
        name: "黄南州",
        mark: "H",
        en: "huangnanzhou"
    }, {
        id: "463",
        name: "海南州",
        mark: "H",
        en: "hainanzhou"
    }, {
        id: "464",
        name: "果洛州",
        mark: "G",
        en: "guoluozhou"
    }, {
        id: "465",
        name: "玉树州",
        mark: "Y",
        en: "yushuzhou"
    }, {
        id: "466",
        name: "海西州",
        mark: "H",
        en: "haixizhou"
    }]
}, {
    id: "30",
    name: "宁夏",
    mark: "N",
    en: "ningxia",
    l2: [{
        id: "467",
        name: "银川市",
        mark: "Y",
        en: "yinchuanshi"
    }, {
        id: "468",
        name: "石嘴山市",
        mark: "S",
        en: "shizuishanshi"
    }, {
        id: "469",
        name: "吴忠市",
        mark: "W",
        en: "wuzhongshi"
    }, {
        id: "470",
        name: "固原市",
        mark: "G",
        en: "guyuanshi"
    }, {
        id: "471",
        name: "中卫市",
        mark: "Z",
        en: "zhongweishi"
    }]
}, {
    id: "31",
    name: "新疆",
    mark: "X",
    en: "xinjiang",
    l2: [{
        id: "472",
        name: "乌鲁木齐市",
        mark: "W",
        en: "wulumuqishi"
    }, {
        id: "473",
        name: "克拉玛依市",
        mark: "K",
        en: "kelamayishi"
    }, {
        id: "474",
        name: "吐鲁番地区",
        mark: "T",
        en: "tulufandiqu"
    }, {
        id: "475",
        name: "哈密地区",
        mark: "H",
        en: "hamidiqu"
    }, {
        id: "476",
        name: "昌吉州",
        mark: "C",
        en: "changjizhou"
    }, {
        id: "477",
        name: "博州",
        mark: "B",
        en: "bozhou"
    }, {
        id: "478",
        name: "巴州",
        mark: "B",
        en: "bazhou"
    }, {
        id: "479",
        name: "阿克苏地区",
        mark: "A",
        en: "akesudiqu"
    }, {
        id: "480",
        name: "克州",
        mark: "K",
        en: "kezhou"
    }, {
        id: "481",
        name: "喀什地区",
        mark: "K",
        en: "kashidiqu"
    }, {
        id: "482",
        name: "和田地区",
        mark: "H",
        en: "hetiandiqu"
    }, {
        id: "483",
        name: "伊犁州",
        mark: "Y",
        en: "yilizhou"
    }, {
        id: "484",
        name: "塔城地区",
        mark: "T",
        en: "tachengdiqu"
    }, {
        id: "485",
        name: "阿勒泰地区",
        mark: "A",
        en: "aletaidiqu"
    }, {
        id: "486",
        name: "石河子市",
        mark: "S",
        en: "shihezishi"
    }, {
        id: "487",
        name: "阿拉尔市",
        mark: "A",
        en: "alaershi"
    }, {
        id: "488",
        name: "图木舒克市",
        mark: "T",
        en: "tumushukeshi"
    }, {
        id: "489",
        name: "五家渠市",
        mark: "W",
        en: "wujiaqushi"
    }]
}, {
    id: "32",
    name: "台湾",
    mark: "T",
    en: "taiwan",
    l2: [{
        id: "490",
        name: "台北市",
        mark: "T",
        en: "taibeishi"
    }, {
        id: "491",
        name: "高雄市",
        mark: "G",
        en: "gaoxiongshi"
    }, {
        id: "492",
        name: "基隆市",
        mark: "J",
        en: "jilongshi"
    }, {
        id: "493",
        name: "新竹市",
        mark: "X",
        en: "xinzhushi"
    }, {
        id: "494",
        name: "台中市",
        mark: "T",
        en: "taizhongshi"
    }, {
        id: "495",
        name: "嘉义市",
        mark: "J",
        en: "jiayishi"
    }, {
        id: "496",
        name: "台南市",
        mark: "T",
        en: "tainanshi"
    }, {
        id: "497",
        name: "台北县",
        mark: "T",
        en: "taibeixian"
    }, {
        id: "498",
        name: "桃园县",
        mark: "T",
        en: "taoyuanxian"
    }, {
        id: "499",
        name: "新竹县",
        mark: "X",
        en: "xinzhuxian"
    }, {
        id: "500",
        name: "苗栗县",
        mark: "M",
        en: "miaolixian"
    }, {
        id: "501",
        name: "台中县",
        mark: "T",
        en: "taizhongxian"
    }, {
        id: "502",
        name: "彰化县",
        mark: "Z",
        en: "zhanghuaxian"
    }, {
        id: "503",
        name: "南投县",
        mark: "N",
        en: "nantouxian"
    }, {
        id: "504",
        name: "云林县",
        mark: "Y",
        en: "yunlinxian"
    }, {
        id: "505",
        name: "嘉义县",
        mark: "J",
        en: "jiayixian"
    }, {
        id: "506",
        name: "台南县",
        mark: "T",
        en: "tainanxian"
    }, {
        id: "507",
        name: "高雄县",
        mark: "G",
        en: "gaoxiongxian"
    }, {
        id: "508",
        name: "屏东县",
        mark: "P",
        en: "pingdongxian"
    }, {
        id: "509",
        name: "宜兰县",
        mark: "Y",
        en: "yilanxian"
    }, {
        id: "510",
        name: "花莲县",
        mark: "H",
        en: "hualianxian"
    }, {
        id: "511",
        name: "台东县",
        mark: "T",
        en: "taidongxian"
    }, {
        id: "512",
        name: "澎湖县",
        mark: "P",
        en: "penghuxian"
    }, {
        id: "513",
        name: "金门县",
        mark: "J",
        en: "jinmenxian"
    }, {
        id: "514",
        name: "连江县",
        mark: "L",
        en: "lianjiangxian"
    }]
}, {
    id: "33",
    name: "香港",
    mark: "X",
    en: "xianggang",
    l2: [{
        id: "515",
        name: "中西区",
        mark: "Z",
        en: "zhongxiqu"
    }, {
        id: "516",
        name: "东区",
        mark: "D",
        en: "dongqu"
    }, {
        id: "517",
        name: "南区",
        mark: "N",
        en: "nanqu"
    }, {
        id: "518",
        name: "湾仔区",
        mark: "W",
        en: "wanziqu"
    }, {
        id: "519",
        name: "九龙城区",
        mark: "J",
        en: "jiulongchengqu"
    }, {
        id: "520",
        name: "观塘区",
        mark: "G",
        en: "guantangqu"
    }, {
        id: "521",
        name: "深水埗区",
        mark: "",
        en: ""
    }, {
        id: "522",
        name: "黄大仙区",
        mark: "H",
        en: "huangdaxianqu"
    }, {
        id: "523",
        name: "油尖旺区",
        mark: "Y",
        en: "youjianwangqu"
    }, {
        id: "524",
        name: "离岛区",
        mark: "L",
        en: "lidaoqu"
    }, {
        id: "525",
        name: "葵青区",
        mark: "K",
        en: "kuiqingqu"
    }, {
        id: "526",
        name: "北区",
        mark: "B",
        en: "beiqu"
    }, {
        id: "527",
        name: "西贡区",
        mark: "X",
        en: "xigongqu"
    }, {
        id: "528",
        name: "沙田区",
        mark: "S",
        en: "shatianqu"
    }, {
        id: "529",
        name: "大埔区",
        mark: "D",
        en: "dapuqu"
    }, {
        id: "530",
        name: "荃湾区",
        mark: "Q",
        en: "quanwanqu"
    }, {
        id: "531",
        name: "屯门区",
        mark: "T",
        en: "tunmenqu"
    }, {
        id: "532",
        name: "元朗区",
        mark: "Y",
        en: "yuanlangqu"
    }]
}, {
    id: "34",
    name: "澳门",
    mark: "A",
    en: "aomen",
    l2: [{
        id: "533",
        name: "花地玛堂区",
        mark: "H",
        en: "huadimatangqu"
    }, {
        id: "534",
        name: "圣安多尼堂区",
        mark: "S",
        en: "shenganduonitangqu"
    }, {
        id: "535",
        name: "大堂区",
        mark: "D",
        en: "datangqu"
    }, {
        id: "536",
        name: "望德堂区",
        mark: "W",
        en: "wangdetangqu"
    }, {
        id: "537",
        name: "风顺堂区",
        mark: "F",
        en: "fengshuntangqu"
    }]
}];